name: PR Size Checker
on:
  pull_request:
  branches:
    - develop

jobs:
  linter_name:
    name: runner / check-pr-size
    runs-on: ubuntu-latest
    steps:
      - uses: budougumi0617/action-pr-size-checker@5ef71f72c7709906031d5d9031d69f6fa13b92a8
        with:
          github_token: ${{ secrets.github_token }}
          max_added_count: 400
          filter_pattern: '.*\.lock|.*\.json|.*\.txt|.*\.sql|.*\.css|.*\.css|.*\.yml|.*\.yaml|.*\.md|'
